# Generated by Django 6.0.4 on 2026-04-22 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('employeeRole', models.CharField(choices=[('Mechanic', 'Mechanic'), ('Salesperson', 'Salesperson'), ('Billing', 'Billing')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Inventory', 'Inventory'), ('Sold', 'Sold'), ('In-Service', 'In Service')], default='Inventory', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('paymentMethod', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Debit', 'Debit'), ('Financing', 'Financing'), ('Check', 'Check')], max_length=9)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivalMileage', models.IntegerField()),
                ('departureMileage', models.IntegerField()),
                ('estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.billing')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSold', models.DateField()),
                ('tagNumber', models.CharField(max_length=20, unique=True)),
                ('customizations', models.TextField(blank=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.billing')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.customer')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='models.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Main Lot', 'Main Lot'), ('Remote Lot', 'Remote Lot'), ('Other Dealership', 'Other Dealership'), ('In Transit', 'In Transit')], default='Main Lot', max_length=17)),
                ('note', models.TextField(blank=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='models.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='WorkedOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.employee')),
                ('serviceData', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.servicedata')),
            ],
        ),
    ]
