# Generated by Django 6.0.4 on 2026-04-23 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employeeRole',
        ),
    ]
