# Generated by Django 6.0.4 on 2026-04-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_remove_employee_employeerole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
